name: google_ml_kit_example
description: Demonstrates how to use the google_ml_kit plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.3.3
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  # The default Android implementation from camera_android_camerax doesn't support the required image format.
  camera_android: ^0.10.9+17
  path: ^1.9.0
  path_provider: ^2.1.4
  google_mlkit_object_detection: ^0.14.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  provider: ^6.1.2
  flutter_svg: ^2.0.17
  image: ^4.5.2
  intl: ^0.20.2

dev_dependencies:
  flutter_lints: ^5.0.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/ml/
    - assets/images/
  fonts:
    - family: Space Gortex
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
